
all:
	make -C src
	#make -C bz20RU
	make -C bz20test
	#make -C httpserver

clean:
	make -C src clean
	make -C bz20RU clean
	make -C bz20test clean
	make -C httpserver clean

install:
	make -C bz20RU install
	make -C bz20test install
	make -C httpserver install
