
all:
	make -C command
	make -C talise
	make -C fft

clean:
	make -C command clean
	make -C talise clean
	make -C fft clean

install:
	make -C command install
	make -C talise install
	make -C fft install
